import { formatDuration, formatStatusCounts } from "./format";
import type { EndpointGroup } from "./types";

function escapeMarkdown(value: string): string {
  return value.replace(/([\\`*_{}[\]()#+.!|-])/g, "\\$1");
}

function code(value: string | number | undefined): string {
  return `\`${String(value ?? "-").replace(/`/g, "\\`")}\``;
}

function endpointTable(groups: EndpointGroup[]): string[] {
  if (!groups.length) {
    return ["No endpoints captured."];
  }

  return [
    "| Method | Endpoint | Origin | Requests | Status | Avg |",
    "| --- | --- | --- | ---: | --- | ---: |",
    ...groups.map((group) =>
      [
        code(group.method.toUpperCase()),
        code(group.pathTemplate),
        code(group.origin),
        group.count.toString(),
        escapeMarkdown(formatStatusCounts(group.statusCounts)),
        formatDuration(group.averageDurationMs)
      ].join(" | ")
    )
  ];
}

function endpointDetails(groups: EndpointGroup[]): string[] {
  return groups.flatMap((group) => {
    const sample = group.samples[0];
    const queryNames = Array.from(new Set(group.samples.flatMap((item) => item.query.map((query) => query.name))));

    return [
      `### ${escapeMarkdown(group.method.toUpperCase())} ${code(group.pathTemplate)}`,
      "",
      `- Origin: ${code(group.origin)}`,
      `- Observed requests: ${group.count}`,
      `- Status pattern: ${escapeMarkdown(formatStatusCounts(group.statusCounts))}`,
      `- Average duration: ${formatDuration(group.averageDurationMs)}`,
      `- Query parameters: ${queryNames.length ? queryNames.map(code).join(", ") : "None observed"}`,
      `- Sample MIME type: ${sample?.mimeType ? code(sample.mimeType) : "Not captured"}`,
      ""
    ];
  });
}

export function buildMarkdownReport(groups: EndpointGroup[], title = "Captured API"): string {
  const sortedGroups = [...groups].sort((left, right) =>
    left.origin.localeCompare(right.origin) || left.pathTemplate.localeCompare(right.pathTemplate) || left.method.localeCompare(right.method)
  );
  const origins = Array.from(new Set(sortedGroups.map((group) => group.origin)));
  const requestCount = sortedGroups.reduce((total, group) => total + group.count, 0);

  return [
    `# ${escapeMarkdown(title)}`,
    "",
    "Generated by API Cartographer from browser DevTools network traffic.",
    "",
    "## Summary",
    "",
    `- Endpoints: ${sortedGroups.length}`,
    `- Requests: ${requestCount}`,
    `- Origins: ${origins.length}`,
    "",
    "## Endpoint Map",
    "",
    ...endpointTable(sortedGroups),
    "",
    "## Endpoint Details",
    "",
    ...endpointDetails(sortedGroups)
  ].join("\n").trimEnd() + "\n";
}
